### ISSUE TITLE
Question about your statusline

### ISSUE THREAD

**Issue by kshenoy** [blaenk/dots#1]
Hi, I copied over [these lines](https://github.com/blaenk/dots/blob/90cc652301c1f731ec6727045bdb81b691879f75/vim/.vimrc#L244-L409) pertaining to your statusline code to my vimrc. I had to comment the section about Fugitive since I don't use it but other than that everything works well. I also copied your solarized colorscheme since you seem to have added custom highlight groups to it.

When I pull up CtrlP the statusline changes like I've moved to another window eg. arrows around the filename invert. I can't figure out how this is done. I don't know which autocmd gets triggered when opening CtrlP that causes s:RefreshStatus() which calls Status().

**Comment by blaenk** [comment]
Hello kshenoy,

I've actually moved to using Emacs + Evil (basically Emacs + Vim), so it's been a while since I've played around with my vim configuration. If I recall correctly, there's nothing special about how I configure CtrlP to make it exhibit the behavior you're referencing. Instead, I think it naturally falls out of the fact (?) that CtrlP is a separate window, and like you said, when you move to a different window the statuslines change, in general, to emphasize the currently active one. That behavior is something I implemented myself.

Have you had a chance to [read through my blog post](http://www.blaenkdenum.com/posts/a-simpler-vim-statusline/#inactive-statuslines) which goes over my custom statusline? The specific section I linked to covers the behavior of keeping track of which window is the active one.

**Comment by kshenoy** [comment]
Hey Blaenk, I needed to RTFM a couple of times before I realized what my mistake was. I came across your blog post first and like the simplicity of the statusline. Thanks for writing a detailed post.

**Comment by blaenk** [comment]
No problem. Glad you were able to figure it out.
