### ISSUE TITLE
.gitconfg [user] field

### ISSUE THREAD

**Issue by srustamo** [blaenk/dots#3]
How do you handle the `[user]` field?

**Comment by blaenk** [comment]
At the end of `~/.gitconfig` another file at `~/.gitconfig.local` is included:

```ini
[include]
	path = ~/.gitconfig.local
```

this file is where I store my `[user]` block and other private or personal information, and I don't track it in the git repo. Also, since it's included at the end of `.gitconfig`, it can override any other properties set in `.gitconfig`.

`.gitconfig.local` is the same file format as `.gitconfig`.

I've added a note of this in 56ee30aa9cf88dba314866f528742033990e2726

**Comment by srustamo** [comment]
Thanks.
